steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/zelarsoft-data-engineering/ml-oops/my-app', '.']
images:
  - 'us-central1-docker.pkg.dev/zelarsoft-data-engineering/ml-oops/my-app'